More v6 test
configcat/android-sdk pull request #47
Opened 2024-02-06 15:59 UTC by novalisdenahi

### Describe the purpose of your pull request

Improvements/Fixes:
- Add target rule percentage options to `getKeyAndValue` and `getKeyAndValueAsync` results.
- Improve double user attribute convert to String
- Added extra config v6 evaluation tests
- Error message and java doc improvements

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2024-02-08 11:01 UTC, adams85 requested changes
So far, so good. 👍 

IIRC, we have two issues left:
* [x] Allow missing config json salt when it is not needed for the evaluation. See: https://github.com/configcat/dart-sdk/pull/26#discussion_r1481219785
* [x] Use the platform's line terminator char sequence in log messages. See also: https://stackoverflow.com/questions/207947/how-do-i-get-a-platform-independent-new-line-character

2024-02-08 22:48 UTC, adams85 requested changes

2024-02-08 22:48 UTC, adams85 commented on src/main/java/com/configcat/RolloutEvaluator.java
> +                return evaluateIsOneOf(userCondition, ensureConfigSalt(configSalt), contextSalt, userAttributeForIsOneOf, negateIsOneOf, sensitiveIsOneOf);
Let's require the config salt in the case of sensitive comparators only.

2024-02-09 15:03 UTC, adams85 approved these changes

2024-02-12 09:27 UTC, z4kn4fein approved these changes

2024-02-13 14:27 UTC, merged